# ==============================================================================
# Reusable composite action: Setup Java 21 + Maven with dependency caching.
#
# WHY: Every workflow needs the same JDK + Maven setup. Extracting it into a
# reusable action eliminates duplication and ensures consistency across
# ci-pr.yml, ci-main.yml, proto-validate.yml, and docker-build.yml.
# ==============================================================================
name: 'Setup Java 21 + Maven'
description: 'Install Eclipse Temurin JDK 21, cache Maven dependencies, and make mvnw executable.'

inputs:
  java-version:
    description: 'JDK version to install'
    required: false
    default: '21'

runs:
  using: 'composite'
  steps:
    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java-version }}
        cache: 'maven'

    - name: Make Maven wrapper executable
      shell: bash
      run: chmod +x ./mvnw
